INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Category Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Category List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Category Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Category Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Category View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Variant Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Variant List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Variant Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Variant Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Variant View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('HSN/SAC Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('HSN/SAC List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('HSN/SAC Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('HSN/SAC Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('HSN/SAC View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Product Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Product List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Product Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Product Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Product View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRPoint Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRPoint List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRPoint Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRPoint Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRPoint View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRCode Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRCode List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRCode Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRCode Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('QRCode View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Video Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Video List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Video Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Video Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Video View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Gallery Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Gallery List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Gallery Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Gallery Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Gallery View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Feedback Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Feedback List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Feedback Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Feedback Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Feedback View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Redeem Data View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Redeem Data Import', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Redeem Data Export', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Our Catalogue Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Our Catalogue List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Our Catalogue Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Our Catalogue Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Our Catalogue View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu User Report', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('User Report Export', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Event Report', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Event Report Export', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Role Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Role List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Role Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Role Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Role View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Permission Create', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Permission List', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Permission Edit', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Permission Delete', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Permission View', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Dashboard', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu User Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Product Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu QR Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Event Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Video Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Gallery Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Feedback Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Account Management', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Our Catalogue', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Report', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Langugae String Master', 'web');
INSERT INTO `permissions` (`name`, `guard_name`) VALUES('Menu Role and Permission', 'web');